language: python
python:
  - "3.6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc

install:
  - pip install pipenv
  - pipenv install

script:
  - make html
  - cp README.md html/

branches:
  only:
    - master

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep_history: false
  local_dir: html
  on:
    branch: master
  
